version: '3.1'

services:
  app:
    build: ./docker/php-apache
    image: ${PHP_VERSION}-apache-composer
    container_name: ${APP_NAME}-php
    tty: true
    volumes:
      - ./:/var/www/html/
      - ./docker/php-apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php-apache/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 9999:80
    depends_on:
      - mongo
  mongo:
    image: 'mongo:4'
    restart: always
    container_name: ${APP_NAME}-mongo-v4
    tty: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    ports:
      - 27017:27017
    command: mongod
    volumes:
      - ./docker/mongo/data:/data/db
      - ./docker/mongo/init/:/docker-entrypoint-initdb.d/
  mongo-express:
    image: mongo-express
    restart: always
    container_name: ${APP_NAME}-mongo-express
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINGUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINGPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${APP_NAME}-mongo-v4
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mongo
volumes:
  mongo: {}
