version: '3.1'

services:
  php:
    build: ./docker/php-apache
    image: php7.2-apache-composer
    container_name: ${APP_NAME}-php
    tty: true
    volumes:
      - ./:/var/www/html/
      - ./docker/php-apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php-apache/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 80:80
    depends_on:
      - postgres
      - mongo
  postgres:
    build: ./docker/postgres
    image: postgres-11.6
    container_name: ${APP_NAME}-postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
      DATABASE_HOST: postgres
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  mongo:
    image: mongo
    build: ./docker/mongo
    restart: always
    container_name: ${APP_NAME}-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 27017:27017
      - 27018:27018
    command: mongod --smallfiles
    volumes:
      - ./docker/mongo/data:/data/db
      - ./docker/mongo/configdb:/data/configdb
  mongo-express:
    image: mongo-express
    # links:
    #   - mongo:mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINGUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINGPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_OPTIONS_EDITORTHEME: ${DB_EDITORTHEME}
    depends_on:
      - mongo
volumes:
  postgres:
  # mongo-data:
  #   driver: local
  # mongo-config:
  #   driver: local
